# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('custom-aodv', ['core'])
    module.source = [
				'model/RoutingProtocol.cc',
				'model/aodv_rreq.cc',
				'model/aodv_rrep.cc',
				'model/aodv_rerr.cc',
				'model/aodv.cc',
				'model/aodv_routing_table.cc',
				'model/send_packet.cc',
        ]

    module_test = bld.create_ns3_module_test_library('custom-aodv')
    module_test.source = [
        ]

    headers = bld(features='ns3header')
    headers.module = 'custom-aodv'
    headers.source = [

        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

