# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('network-monitoring', ['core'])
    module.source = [
        'model/network-monitoring.cc',
        'helper/network-monitoring-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('network-monitoring')
    module_test.source = [
        'test/network-monitoring-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'network-monitoring'
    headers.source = [
        'model/network-monitoring.h',
        'helper/network-monitoring-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

